import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex m-5">
          <nav className="flex flex-col mr-10">
            <p className="uppercase">Server Components</p>
            <ul className="">
              <li>
                <a className="underline" href="">
                  Static Rendering
                </a>
              </li>
              <li>
                <a className="underline" href="">
                  Dyanamic Rendering
                </a>
              </li>
              <li>
                <a className="underline" href="">
                  Streaming
                </a>
              </li>
            </ul>
          </nav>
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  )
}
